### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [itsmanojsoni/nytimes#1]
:+1: Great work! A few notes after checking out the code:

* Properly reused the single base method in search activity to fetch results for both initial load and the pagination
* Properly used spinners/checkboxes (with populated values) to allow users to select filters
* Great job implementing `DialogFragment` for filters.
* Try to externalize code for internet check to `Utils`. Also you might need to call `cm.getActiveNetworkInfo().isConnected();` in addition to the null check to see if your device is connected to wifi/radio.
* Nice to see you added the search box to the `Toolbar`!
* Nice job adding the share intent to the article detail view!
* Nice to see you used the new [date picker](http://guides.codepath.com/android/Using-DialogFragment#displaying-date-or-time-picker-dialogs) dialog. 

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission.

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.

**Comment by itsmanojsoni** [comment]
Thanks for the feedback. I was wondering if anything changed on the report card after reviewing it again. Thanks Again and really appreciate the work you guys are doing.

**Comment by codepathreview** [comment]
Well, the first score that you saw was just a bug on our tool. We usually have a 2 step process (screening & code review) and you weren't supposed to see the initial score. Its fixed now and shouldn't be happening in future. Thanks for your patience.

**Comment by itsmanojsoni** [comment]
Thanks!
